-- Inserting data into the "questions" table

INSERT INTO "questions" ("id", "statement", "answer", "explanation", "attempts", "correct_answers")
VALUES 
  ('dd6cbf48-1ef6-426c-beef-2e0f1ec88c2c', 'Le recyclage ne sert à rien, tout finit par être jeté dans la même décharge.', false, 'Le recyclage permet de réutiliser des matériaux qui ne sont pas biodégradables. Il permet de réduire la quantité de déchets et de limiter l''exploitation des ressources naturelles.', 0, 0),
  ('a7cdb501-c06f-4ad7-a7b1-d3878303ed99', 'Les énergies renouvelables sont plus polluantes que les énergies fossiles.', false, 'Les énergies renouvelables sont moins polluantes que les énergies fossiles. Elles sont produites à partir de ressources naturelles qui se renouvellent en permanence.', 0, 0),
  ('f164225c-4e3f-4f83-a74c-34e2ea538a5b', 'Les voitures ne polluent pas tant que ça', false, 'Les voitures polluent beaucoup. Elles rejettent des gaz toxiques qui contribuent au réchauffement climatique.', 0, 0),
  ('879b6ac1-347f-4952-a478-eebe43f8d1f3', 'Les déchets sont biodégradables', false, 'Les déchets ne sont pas tous biodégradables. Certains déchets comme le plastique ne se décomposent pas naturellement.', 0, 0),
  ('36c21113-1990-45ca-9786-b05effdf45a2', 'La transition énergétique, c''est surtout le passage aux énergies renouvelables électriques', false, 'La transition énergétique, c''est le passage à une économie qui consomme moins d''énergie et qui utilise des énergies renouvelables.', 0, 0),
  ('43025977-fb07-40da-8cff-68b2afca8d93', 'Garder sa vieille voiture, c''est mieux pour l''environnement', true, 'Garder sa vieille voiture, c''est mieux pour l''environnement. La fabrication d''une voiture neuve est très polluante, dans la mesure du possible, il faut garder sa voiture le plus longtemps possible.', 0, 0),
  ('7f49d1b3-22bb-4a8b-9f36-1a384676b04a', 'L''utilisation de l''énergie solaire ne contribue pas significativement à la réduction des émissions de gaz à effet de serre.', false, 'L''énergie solaire est une source propre qui contribue à réduire les émissions de gaz à effet de serre en produisant de l''électricité sans émission directe de polluants.', 0, 0),
  ('8e6a0b8d-d31c-4919-9d7e-5a72c4f413e2', 'Les empreintes écologiques individuelles n''ont pas d''impact réel sur l''environnement global.', false, 'Les empreintes écologiques individuelles cumulées ont un impact significatif sur l''environnement. Les choix de consommation et de mode de vie peuvent influencer la durabilité.', 0, 0),
  ('4a3e35f5-7f4b-4bfc-9b09-1c02a7a4f378', 'Le compostage est une méthode efficace pour réduire la quantité de déchets organiques en décharge.', true, 'Le compostage permet de transformer les déchets organiques en un engrais naturel, réduisant ainsi la quantité de déchets envoyés en décharge.', 0, 0),
  ('6a468b3c-c9e2-4d04-bbdf-9365a03cf7e0', 'Les forêts plantées peuvent compenser complètement la déforestation.', false, 'Les forêts plantées ne peuvent pas toujours compenser complètement la biodiversité et les fonctions écologiques perdues lors de la déforestation.', 0, 0),
  ('baa6ff01-d60e-4a22-a0b8-0806344225ec', 'L''utilisation de l''énergie nucléaire est la solution idéale pour lutter contre le changement climatique.', false, 'L''énergie nucléaire est une source à faible émission de carbone, mais elle suscite des débats en raison des préoccupations liées à la sécurité, à la gestion des déchets et à d''autres problèmes.', 0, 0),
  ('9a0e1abf-1baa-4bf8-a552-6aa8c6b6f13d', 'La consommation de viande rouge n''a aucun impact sur l''environnement.', false, 'La production de viande rouge a un impact environnemental important en termes d''utilisation des ressources, de déforestation et d''émissions de gaz à effet de serre.', 0, 0);
