name: "Quality of Code"

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    # paths:
    #   - "web/**"

env:
  PATH_TO_DOCKERFILE: .
  WEB_DIR: web
  API_DIR: api

jobs:
  web-report:
    name: Lint and Check SPA
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WEB_DIR }}
    outputs:
      quality: ${{ steps.quality.outputs.quality }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2.4.0
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ESLint
        run: pnpm run lint

      - id: quality
        if: always()
        run: |
          if [[ steps.lint.conclusion == 'success' ]]
          then
            echo 'quality="Ton code est OK"' >> "$GITHUB_OUTPUT"
          else
            echo 'quality="Ton code est KO"' >> "$GITHUB_OUTPUT"
          fi

  api-report:
    name: Lint and Check API
    runs-on: ubuntu-latest
    outputs:
      quality: ${{ steps.quality.outputs.quality }}
    defaults:
      run:
        working-directory: ${{ env.API_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable
        name: Install the Rust toolchain

      - uses: Swatinem/rust-cache@v2
        name: Use cached dependencies and artifacts

      - uses: arduino/setup-protoc@v2
        name: Install Protoc

      - name: Check cargo build
        run: cargo build --release --all-features --verbose

      - id: check
        name: Check formatting
        if: always()
        run: cargo fmt --check

      - id: lint
        name: Run lint
        if: always()
        run: cargo clippy -- -D warnings

      - id: quality
        if: always()
        run: |
          if [[ steps.check.conclusion == 'success' && steps.lint.conclusion == 'success' ]]
          then
            echo 'quality="Ton code est OK"' >> "$GITHUB_OUTPUT"
          else
            echo 'quality="Ton code est KO"' >> "$GITHUB_OUTPUT"
          fi

  docker-report:
    name: KICS Trigger
    runs-on: ubuntu-latest
    outputs:
      quality: ${{ steps.quality.outputs.quality }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: run kics Scan
        id: scan
        uses: checkmarx/kics-github-action@v1.7.0
        with:
          path: ${{ env.PATH_TO_DOCKERFILE }}
          fail_on: high
          output_path: results-dir
          type: Dockerfile

      - name: display kics results
        run: |
          cat results-dir/results.json

      - id: quality
        if: always()
        run: |
          if [[ steps.scan.conclusion == 'success' ]]
          then
            echo 'quality="Ton container est OK"' >> "$GITHUB_OUTPUT"
          else
            echo 'quality="Ton container est KO"' >> "$GITHUB_OUTPUT"
          fi

  pr-comment:
    if: always()
    name: PR comment
    runs-on: ubuntu-latest
    needs:
      - web-report
      - api-report
      - docker-report
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            {
              "actor" : "${{ github.actor }}",
              "web_code": ${{ needs.web-report.outputs.quality }},
              "api_code": ${{ needs.api-report.outputs.quality }},
              "container": ${{ needs.docker-report.outputs.quality }}
            }
